[package]
name = "NotSoTurboPuffer"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
aws-config = "1.10.1"
aws-sdk-s3 = "1.140.0"
chrono = "0.4.45"
dotenvy = "0.15.7"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
toml = "1.1.4"
tracing = "0.1.44"
